In [1]:
import torch

In [2]:
t = torch.arange(27).reshape((3,3,3))

In [17]:
_i = torch.arange(3, dtype=torch.long)
index0 = _i.expand(3,3, -1).permute(2,1,0)
index0

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]])

In [18]:
_i = torch.arange(3, dtype=torch.long)
index1 = _i.expand(3,3, -1).permute(0,2,1)
index1

tensor([[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]]])

In [19]:
_i = torch.arange(3, dtype=torch.long)
index2 = _i.expand([3,3,-1])
index2

tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]])

In [ ]:
x,y,z = list(t.shape)
p = []
for i in range(x):
    q = []
    for j in range(y):
        r = []
        for k in range(z):
            r.append(t[i][j][index2[i][j][k]])
        q.append(r)
    p.append(q) 
torch.tensor(p)

In [ ]:
torch.gather(t, 0, index=index0)

In [ ]:
torch.gather(t, 1, index=index1)

In [ ]:
torch.gather(t, 2, index=index2)